# Autogenerated by nbdev

d = { 'settings': { 'branch': '{branch}',
                'doc_baseurl': '/nbcleanse/',
                'doc_host': 'https://{user}.github.io',
                'git_url': 'https://github.com/{user}/{repo}/',
                'lib_path': 'nbcleanse'},
  'syms': {}}
